/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as CaraBeliRouteImport } from './routes/cara-beli'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIdRouteImport } from './routes/account.$id'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraBeliRoute = CaraBeliRouteImport.update({
  id: '/cara-beli',
  path: '/cara-beli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIdRoute = AccountIdRouteImport.update({
  id: '/account/$id',
  path: '/account/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cara-beli': typeof CaraBeliRoute
  '/kontak': typeof KontakRoute
  '/stock': typeof StockRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cara-beli': typeof CaraBeliRoute
  '/kontak': typeof KontakRoute
  '/stock': typeof StockRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cara-beli': typeof CaraBeliRoute
  '/kontak': typeof KontakRoute
  '/stock': typeof StockRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cara-beli' | '/kontak' | '/stock' | '/account/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cara-beli' | '/kontak' | '/stock' | '/account/$id'
  id: '__root__' | '/' | '/cara-beli' | '/kontak' | '/stock' | '/account/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaraBeliRoute: typeof CaraBeliRoute
  KontakRoute: typeof KontakRoute
  StockRoute: typeof StockRoute
  AccountIdRoute: typeof AccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-beli': {
      id: '/cara-beli'
      path: '/cara-beli'
      fullPath: '/cara-beli'
      preLoaderRoute: typeof CaraBeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$id': {
      id: '/account/$id'
      path: '/account/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaraBeliRoute: CaraBeliRoute,
  KontakRoute: KontakRoute,
  StockRoute: StockRoute,
  AccountIdRoute: AccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
